apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    env: demo 
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    env: demo
      