apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
  labels:
    env: demo
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      targetPort: 80
      port: 80
      protocol: TCP
  selector: 
    env: demo
    type: frontend