apiVersion: apps/v1
kind: ReplicaSet 
metadata: 
  name: nginx-rs 
  labels:  
    env: demo
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        env: demo
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx 
  replicas: 3
  selector:
    matchLabels:
      env: demo 